### ISSUE TITLE
Problems with capture a new video

### ISSUE THREAD

**Issue by haumichel** [jameszah/ESP32-CAM-Video-Recorder#57]
Hi all,

when I try to record a new video via http command. Desklens always tells me that I have to stop recording first.
When I stop recording (http://ip-address/stop) and try again, Desklens tells me that I have to stop recording first.
Only after pressing the reset button, I can create a new video.
What am I doing wrong?

Thank you

**Comment by jameszah** [comment]
It won't work if you "stop" and the backup in your browser.  It will still think it is stopped.  So you have to backup and refresh, and then it will work.  I few lines of Javascript would sort it out, but it was originally made for another computer to send that url, rather than a human with a browser.
