### ISSUE TITLE
Creating Realtime videos 

### ISSUE THREAD

**Issue by amansinghaljpr** [jameszah/ESP32-CAM-Video-Recorder#58]
First of all great job buddy ! 

So if i make a camcorder using this library , the problem i incur is of recording a realtime video , its always a fast forward timelapse kinda video . Which parameter do i change to make it record a realtime video .

**Comment by jameszah** [comment]
If you are driving the video from the settings.h parameters, you need to set this xspeed to 1

https://github.com/jameszah/ESP32-CAM-Video-Recorder/blob/f90207b74c8ac247ef20f3cde9664b5f80844a02/v99/settings.h#L40

If you launch the recording from the url command, then the speed should be 1

![image](https://user-images.githubusercontent.com/36938190/132971470-00565da9-ba94-478e-a435-af4eb7d07c53.png)

Otherwise it calculates the real length of video, divides by the frame count, and plays them at that speed.  
Speed up the playback - like a timelapse with speed > 1, and slow motion with speed < 1
