### ISSUE TITLE
SDCARD

### ISSUE THREAD

**Issue by farisanaklumajang** [jameszah/ESP32-CAM-Video-Recorder#61]
- Jika sdcard full, video lama  tidak otomatis hapus,
   Esp32 juga  malah macet

**Comment by jameszah** [comment]
Do you have this update:

![image](https://user-images.githubusercontent.com/36938190/150730145-ac8a4312-6584-4cb0-99bb-1fd4ad9dff99.png)

https://github.com/jameszah/ESP32-CAM-Video-Recorder/blob/master/vA1/TimeLapseAviA1.5x.ino

https://github.com/jameszah/ESP32-CAM-Video-Recorder/commit/58dc7e9e64399e3efdad4af8c9db3a06b8ab7493

**Comment by farisanaklumajang** [comment]
Saya sudah memakai TImelapseAviA1.5x.ino,,,

**Comment by farisanaklumajang** [comment]
![Screenshot_2022-01-24-18-59-12-815_org telegram messenger](https://user-images.githubusercontent.com/93380309/150779224-5fc6fd22-f4c7-49a6-baad-a08b8604af20.jpg)

RESTART SENDIRI ESP32NYA, TANPA MEREKAM ( KARNA TIDAK BISA MENGHAPUS FILE REKAMAN OLD )

**Comment by jameszah** [comment]
I made the changes for that file delete problem about a week ago.
It was with a new version of the file 1.5x.

I have now changed the naming convention and called it 1x

This is the file you need:

https://github.com/jameszah/ESP32-CAM-Video-Recorder/blob/master/vA1/TimeLapseAviA1x.ino

Old versions can be seen here:

https://github.com/jameszah/ESP32-CAM-Video-Recorder/commits/master/vA1

**Comment by farisanaklumajang** [comment]
Oke siap,
Nanti akan saya coba 👍

**Comment by farisanaklumajang** [comment]
![Screenshot_2022-01-25-09-30-18-137_com miui gallery](https://user-images.githubusercontent.com/93380309/150899855-b71cc6bd-97bb-40a6-9bc2-c6cdbd84bad5.jpg)

Remove dir filed

**Comment by jameszah** [comment]
Try a quick-format in fat32 on a windows or mac.

You might have broken files that are filling up space that appears available.

And the root is "/sdcard" so my computer shows 

/sdcard/20220125/snolens_2022-01-25_00.01.51_vga_Q12_I200_L1800_S1.avi

... so that unprintable ascii chars might mess it up.

https://github.com/espressif/arduino-esp32/blob/6a7bcabd6b7a33f074f93ed60e5cc4378d350b81/libraries/SD_MMC/src/SD_MMC.h#L41
